swagger: '2.0'
info:
  title: Sample API
  description: Optional multiline or single-line description in x
  version: '0.1.9'
schemes: ['http']
host: 0.0.0.0:8080
paths:
  /purchase:
    post:
      summary: add a new purchase
      consumes:
        - application/json
      responses:
        200:
          description: OK
  /purchases:
    get:
      summary: Returns a list of purchases.
      produces:
        - application/json
      responses:
        '200':    # status code
          description: A JSON array of user names
  /purchasesForArticle:
    get:
      summary: Returns a list of the purchases that bought article with given articleID
      responses:
        '200':
          description: OK
  